FuelPricePredictionWeb/core/urls.py
from django.urls import path
from .views import home, predict, dashboard, bar, pie, line, box
from core.dash_apps.finished_apps import simpleexample, barchart, piechart, linechart, boxplot
app_name = 'core'

urlpatterns = [
    path('',home,name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('bar/', bar, name='bar'),
    
    path('pie/', pie, name='pie'),
    path('line/', line, name='line'),
    path('other/', box, name='other'),
    
    
    path('predict/', predict, name='predict'),
]

FuelPricePredictionWeb/fuelpriceprediction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

FuelPricePredictionWeb/core/models.py
from django.db import models

# Create your models here.

FuelPricePredictionWeb/core/views.py
from django.shortcuts import render

# Create your views here.
import joblib
import numpy as np
import pandas as pd


from plotly.offline import plot
import plotly.graph_objects as go

# import pyttsx3

prediction = 0

# engine = pyttsx3.init()  
# voices = engine.getProperty('voices')  # Get all the voices
# engine.setProperty('voice', voices[1].id)  # set it to second voice
# engine.say('Welcome! Predict the fuel prices of Bhutan. Fill the inputs fields and click on the predict button.')  # ask it to say the command
# engine.runAndWait()
# engine.stop()

model = joblib.load('model/model.pkl', "rb")


def home(request):
    
    return render(request,'index.html')

def predict(request):
    try:
        region = [request.POST.get('region')][0]
        product = [request.POST.get('product')][0]
        company = [request.POST.get('company')][0]
        dateinput = [request.POST.get('dateinput')][0]
        station = [request.POST.get('station')][0]
        # nosrm = [request.POST.get('rminput')][0]
        
        # engine = pyttsx3.init()  
        # voices = engine.getProperty('voices')  # Get all the voices
        # engine.setProperty('voice', voices[1].id)  # set it to second voice
        # engine.say('Predicting the price on your input.')  # ask it to say the command
        # engine.runAndWait()
        # engine.stop()
        
        
        if region == "" or product == "" or company == "" or dateinput == "" or station == "":
            context = {'error': 'Please fill the input fields'}
            
            # print("Please fill the input fields")
            # engine = pyttsx3.init()  
            # voices = engine.getProperty('voices')  # Get all the voices
            # engine.setProperty('voice', voices[1].id)  # set it to second voice
            # engine.say('Please fill the input fields.')  # ask it to say the command
            # engine.runAndWait()
            # engine.stop()
            return render(request, 'index.html', context)
        
        else:
        
        # dateinput = [request.POST.get('dateinput')][0].split("-")
        
        # month = dateinput[0]
        # day = dateinput[1]
        # year = dateinput[2]
        
        
        # print(month)
        # print(day)
        # print(year)
        
    #     stations = ['Phuentsholing', 'Rinchending', 'Pasakha', 'Samtse Town', 'Sipsoo',
    #    'Gomtu', 'Gedu', 'Phuentsholing Main gate',
    #    'Gelephu Forest Checkpost', 'Sarpang', 'Gelephu Gate',
    #    'Gelephu Town', 'Dagapela', 'Tsirang', 'Zhemgang', 'Trongsa',
    #    'Bumthang', 'Dagana', 'Lhamoizingkha', 'Dangdung', 'Panbang',
    #    'Tingtibi', 'Samdrup Jongkhar', 'Wamrong', 'Trashigang',
    #    'Trashiyangtse', 'Mongar', 'Gyelposing', 'Kanglung', 'Pemagatshel',
    #    'Lhuntse', 'Jomotsangkha', 'Autsho', 'Doksum', 'Bhangtar',
    #    'Rangjung', 'Nganglam', 'Samdrup Jongkhar Gate',
    #    'Nganglam Potonala', 'Samdrup Jongkhar Upper Town', 'Chimakothi',
    #    'Lungtenzampa', 'Paro Town', 'Haa', 'Bajo Town', 'Beychu',
    #    'Khuruthang', 'Gasa', 'Motithang', 'Olakha', 'Paro NIE Bridge',
    #    'Langlitsawa', 'Wangdue Zero Point', 'Lobesa', 'Chubachu',
    #    'Paro Shaba', 'Samtse Checkpost', 'Pagli', 'Mitsina', 'Dorokha',
    #    'Langdru (Khasadrapchu)', 'Chanzamtok', 'Gomtu Phuentshopelri',
    #    'Phuentsholing Truck Parking', 'Phuentsholing Dungkhag Office',
    #    'Phuentsholing Near MDP', 'Ramtokto', 'Chamkuna LAP,Phuntsholing']
    #     print(len(stations)) # 68
        
        
        # columns = ['Region', 'Product', 'Company', 'Approved_Date', 'Station']
        # sample = [['Western Region', 'Diesel', 'Indian Oil Corporation Limited', '2021-08-16', 'Samtse Checkpost']]
        

            x = [[region, product, company, dateinput, station]]
            print(x)
            
            
            x = pd.DataFrame(x, columns=['Region', 'Product', 'Company', 'Approved_Date', 'Station'])
            
            # print(x)
            # Use the loaded model to make predictions
            prediction = model.predict(x)
            prediction = format(prediction[0], '.3f')  # format to 3 decimals

            context = {'result': prediction, 'input': x}
            
           
            
            
            
            # return render(request,'result.html',context)
        
    except:
        # context = {'error': 'Something went wrong. Please try again by filling the input fields'}
        # engine = pyttsx3.init()  
        # voices = engine.getProperty('voices')  # Get all the voices
        # engine.setProperty('voice', voices[1].id)  # set it to second voice
        # engine.say('Something went wrong. Please try again by giving the correct inputs. ') # ask it to say the command
        # engine.runAndWait()
        # engine.stop()
        return render(request, 'index.html', context)

    # engine = pyttsx3.init()  
    # voices = engine.getProperty('voices')  # Get all the voices
    # engine.setProperty('voice', voices[1].id)  # set it to second voice
    # engine.say('Showing the predicted price... ') # ask it to say the command
    # engine.runAndWait()
    # engine.stop()
    
    return render(request,'index.html',context)


def dashboard(request):
    # def scatter():
    #     x1 = [1,2,3,4]
    #     y1 = [30, 35, 25, 45]

    #     trace = go.Scatter(
    #         x = x1,
    #         y = y1
    #     )
    #     layout = dict(
    #         title='Simple Graph',
    #         xaxis=dict(range=[min(x1), max(x1)]),
    #         yaxis = dict(range=[min(y1), max(y1)])
    #     )

    #     fig = go.Figure(data=[trace], layout=layout)
    #     plot_div = plot(fig, output_type='div', include_plotlyjs=False)
    #     return plot_div

    # context ={
    #     'plot1': scatter()
    # }

    return render(request, 'core/welcome.html')


def bar(request):
    

    return render(request, 'core/barchart.html')

def pie(request):
    

    return render(request, 'core/piechart.html')


def line(request):    

    return render(request, 'core/linechart.html')


def box(request):    

    return render(request, 'core/boxplot.html')

FuelPricePredictionWeb/core/templates/core/barchart.html
{%  extends 'dashbase.html' %}
{% load static %}
{% block content %}
    {% load plotly_dash %}
{% comment %} <h1>Welcome</h1> {% endcomment %}

    <div class="{% plotly_class name='Barchart' %} card" style="height: 100%; width: 100%">
    {% plotly_app name='Barchart' ratio=0.45 %}
    </div>
{% comment %} <br>
    {{ plot1 | safe }} {% endcomment %}

{% endblock %}

FuelPricePredictionWeb/templates/index.html
{% extends 'base.html' %} {% block content%} {% if result %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
{% comment %} <h2 class="head">Fuel Price Prediction Result</h2> {% endcomment %}

<div class="card text-center" style="padding: 22.2%; background-color: #8EC5FC;
      background-image: linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%);
      ">
  
          <h2 style="font-weight: 800;">Result: NU. {{result}}</h2>
  
          <span><a href="{% url 'core:home' %}" class="btn">Predict again?</a></span>
  
  
  
      </div>


{% else %}




      {% if error %}
      <p >{{ error }}</p>
      {% endif %}

<form method="POST", action="{% url 'core:predict' %}">
  
  {% csrf_token %}
  <div class="row">
    <div class="col-25">
      <label for="Gender">Region:</label>
    </div>
    <div class="col-75">
      <select name="region" id="region">
        <option value="Western Region">Western Region</option>
        <option value="Central Region">Central Region</option>
        <option value="Eastern Region">Eastern Region</option>
      </select>
    </div>
  </div>

  <div class="row">
    <div class="col-25">
      <label for="Married">Product:</label>
    </div>
    <div class="col-75">
      <select name="product" id="product">
        <option value="Diesel">Diesel</option>
        <option value="Petrol">Petrol</option>
      </select>
    </div>
  </div>

  
  <div class="row">
    <div class="col-25">
      <label for="Dependents">Company:</label>
    </div>
    <div class="col-75">
      <select name="company" id="company" placeholder="Select Product">
        <option value="Indian Oil Corporation Limited">Indian Oil Corporation Limited</option>
        <option value="Bharat Petroleum Corporation Limited">Bharat Petroleum Corporation Limited</option>
        <option value="Hindustan Petroleum Corporation Limited">Hindustan Petroleum Corporation Limited</option>
      </select>
    </div>
  </div>

  <div class="row">
    <div class="col-25">
      <label for="Education">Approval Date:</label>
    </div>
    <div class="col-75">
      <input type="datetime-local" placeholder="Select Date" id="dtate" name="dateinput">
    </div>
  </div>

 
  <div class="row">
    <div class="col-25">
      <label for="Self_Employed">Station:</label>
    </div>
    <div class="col-75">
      <select name="station" id="station">
              <option value="Phuentsholing">Phuentsholing</option>
              <option value="Rinchending">Rinchending</option>
              <option value="Pasakha">Pasakha</option>
              <option value="SamtseTown">Samtse Town</option>
              <option value="Sipsoo">Sipsoo</option>
              <option value="Gomtu">Gomtu</option>
              <option value="Gedu">Gedu</option>
              <option value="Phuentsholing Main gate">Phuentsholing Main gate</option>
              <option value="Gelephu Forest Checkpost">Gelephu Forest Checkpost</option>
              <option value="Sarpang">Sarpang</option>
              <option value="Gelephu Gate">Gelephu Gate</option>
              <option value="GelephuTown">Gelephu Town</option>

              <option value="Dagapela">Dagapela</option>
              <option value="Tsirang">Tsirang</option>
              <option value="Zhemgang">Zhemgang</option>
              <option value="Trongsa">Trongsa</option>
              <option value="Bumthang">Bumthang</option>
              <option value="Dagana">Dagana</option>
              <option value="Lhamoizingkha">Lhamoizingkha</option>
              <option value="Dangdung">Dangdung</option>
              <option value="Panbang">Panbang</option>
              <option value="Tingtibi">Tingtibi</option>
              <option value="SamdrupJongkhar">Samdrup Jongkhar</option>
              <option value="Wamrong">Wamrong</option>


              <option value="Trashigang">Trashigang</option>
              <option value="Trashiyangtse">Trashiyangtse</option>
              <option value="Mongar">Mongar</option>
              <option value="Gyelposing">Gyelposing</option>
              <option value="Kanglung">Kanglung</option>
              <option value="Pemagatshel">Pemagatshel</option>
              <option value="Jomotsangkha">Jomotsangkha</option>
              <option value="Lhuntse">Lhuntse</option>
              <option value="Autsho">Autsho</option>
              <option value="Doksum">Doksum</option>
              <option value="Bhangtar">Bhangtar</option>
              <option value="Rangjung">Rangjung</option>

              
              <option value="Nganglam">Nganglam</option>
              <option value="Samdrup Jongkhar Gate">Samdrup Jongkhar Gate</option>
              <option value="Nganglam Potonala">Nganglam Potonala</option>
              <option value="Samdrup Jongkhar Upper Town">Samdrup Jongkhar Upper Town</option>
              <option value="Chimakothi">Chimakothi</option>
              <option value="Lungtenzampa">Lungtenzampa</option>
              <option value="Paro Town">Paro Town</option>
              <option value="Haa">Haa</option>
              <option value="BajoTown">Bajo Town</option>
              <option value="Beychu">Beychu</option>
              <option value="Khuruthang">Khuruthang</option>
              <option value="Gasa">Gasa</option>

              <option value="Motithang">Motithang</option>
              <option value="Olakha">Olakha</option>
              <option value="Paro NIE Bridge">Paro NIE Bridge</option>
              <option value="Langlitsawa">Langlitsawa</option>
              <option value="Wangdue Zero Point">Wangdue Zero Point</option>
              <option value="Lobesa">Lobesa</option>
              <option value="Chubachu">Chubachu</option>
              <option value="Paro Shaba">Paro Shaba</option>
              <option value="Samtse Checkpost">Samtse Checkpost</option>
              <option value="Pagli">Pagli</option>
              <option value="Mitsina">Mitsina</option>
              <option value="Dorokha">Dorokha</option>

              <option value="Langdru">Langdru (Khasadrapchu)</option>
              <option value="Chanzamtok">Chanzamtok</option>
              <option value="Gomtu Phuentshopelri">Gomtu Phuentshopelri</option>
              <option value="Phuentsholing Truck Parking">Phuentsholing Truck Parking</option>
              <option value="Phuentsholing Dungkhag Office">Phuentsholing Dungkhag Office</option>
              <option value="Phuentsholing Near MDP">Phuentsholing Near MDP</option>
              <option value="Ramtokto">Ramtokto</option>
              <option value="Chamkuna LAP,Phuntsholing">Chamkuna LAP,Phuntsholing</option>       
      </select>
    </div>
  </div><br><br><br>
  <div class="row" style='align-items:center;'>
    <input type="submit" value="Predict">
  </div>
</form>

{% endif %}
{% endblock %}

FuelPricePredictionWeb/templates/partials/_footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>© 2022 Group 12. All rights reserved</span>
        </div>
    </div>
</footer>

FuelPricePredictionWeb/templates/partials/_sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
        {% comment %} <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div> {% endcomment %}
        <div class="sidebar-brand-text mx-3">PFP</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:dashboard' %}" >
            <i class="fas fa-fw fa-desktop"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interfaces
    </div> 

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'core:bar' %}">
            <i class="fas fa-fw fa-chart-bar"></i>
            <span>Barplots</span>
        </a>
    
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'core:pie' %}">
            <i class="fas fa-fw fa-chart-pie"></i>
            <span>Pie Charts</span>
        </a>
        
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'core:line' %}">
            <i class="fas fa-chart-line"></i>
            <span>Line Charts</span>
        </a>
    
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'core:other' %}">
            <i class="fas fa-calendar-plus"></i>
            <span>Others</span>
        </a>
    
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    {% comment %} <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block"> {% endcomment %}

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    {% comment %} <!-- Sidebar Message -->
    <div class="sidebar-card d-none d-lg-flex">
        <img class="sidebar-card-illustration mb-2" src="img/undraw_rocket.svg" alt="...">
        <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
        <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
    </div> {% endcomment %}

</ul>
<!-- End of Sidebar -->

FuelPricePredictionWeb/templates/result.html
{% comment %} {% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Fuel Price Prediction</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>
  
  <!-- Header -->
  <section id="header">
    <header class="header-area">
        <div class="header-container">
            <div class="site-logo">
                <a href="/">BF<span>PP</span></a>
            </div>
            <div class="mobile-nav">
                <i class="fas fa-bars"></i>
            </div>
            <div class="site-nav-menu">
                <ul class="primary-menu">
                  <li><a href="/" data-after="Home">Home</a></li>
                  <li><a href="#about" data-after="About">About Us</a></li>
                  <li><a href="#contact" data-after="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </header>
  </section>
  <!-- End Header -->
  <section id = "upload" style="background-color: white;">
    <div class="predict" style="margin-top: 40px;">
      <h2 class="head">Bhutans' Fuel Price Prediction</h2>
      <div class="card text-center" style="padding: 22.2%; background-color: #8EC5FC;
      background-image: linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%);
      ">
  
          <h2 style="font-weight: 800;">Result: NU. {{result}}</h2>
  
          <span><a href="{% url 'core:home' %}" class="btn">Predict again?</a></span>
  
  
  
      </div>
  
    </div>
  </section>
  <section id="about" class="about">
     <div class="container1">
         <div class="row1">
             <div class="section-title">
                 <h1>About<span>Us</span></h1>
                 <p>Meet the project team</p>
             </div>
         </div>
         <div class="row1">
             <div class="team-items">
                  <div class="item1">
                      <img src="{% static 'img/01.jpg' %}" alt="team" style="border-radius: 50%; width: 300px; height: 300px; margin-left: 17px;" />
                      <div class="inner">
                          <div class="info">
                               <h5>Ugyen Wangdi</h5>
                               <p>Team Leader</p>
                               <div class="social-links">
                                   <a href="https://www.facebook.com/ughen.wangdi.54379/ " target='_blank'><span class="fa fa-facebook"></span></a>
                                   <a href="https://www.instagram.com" target='_blank'><i class="fab fa-instagram"></i></a>
                                   <a href="https://twitter.com/" target='_blank'><span class="fa fa-twitter"></span></a>
                                   <a href="https://www.youtube.com/" target='_blank'><span class="fa fa-youtube"></span></a>
                               </div>
                          </div>
                      </div>
                  </div>
                  <div class="item1">
                      <img src="{% static 'img/02.JPG' %}" alt="team" style="border-radius: 50%; width: 300px; height: 300px; margin-left: 17px;"/>
                      <div class="inner">
                          <div class="info">
                               <h5>Gyeltshen Wangdi</h5>
                               <p>Backend Developer</p>
                               <div class="social-links">
                                   <a href="https://www.facebook.com/gyltshen.wangdi" target='_blank'><span class="fa fa-facebook"></span></a>
                                   <a href="https://www.instagram.com" target='_blank'><i class="fab fa-instagram"></i></a>
                                   <a href="https://twitter.com/" target='_blank'><span class="fa fa-twitter"></span></a>
                                   <a href="https://www.youtube.com/" target='_blank'><span class="fa fa-youtube"></span></a>
                               </div>
                          </div>
                      </div>
                  </div>
                  <div class="item1">
                      <img src="{% static 'img/03.JPG' %}" alt="team" style="border-radius: 50%; width: 300px; height: 300px; margin-left: 17px;"/>
                      <div class="inner">
                          <div class="info">
                               <h5>Galey Wangmo</h5>
                               <p>UI Designer</p>
                               <div class="social-links">
                                   <a href="https://www.facebook.com/profile.php?id=100004111544909" target='_blank'><span class="fa fa-facebook"></span></a>
                                   <a href="https://www.instagram.com" target='_blank'><i class="fab fa-instagram"></i></a>
                                   <a href="https://twitter.com/" target='_blank'><span class="fa fa-twitter"></span></a>
                                   <a href="https://www.youtube.com/" target='_blank'><span class="fa fa-youtube"></span></a>
                               </div>
                          </div>
                      </div>
                  </div>
                  <div class="item1">
                      <img src="{% static 'img/04.jpg' %}" alt="team" style="border-radius: 50%; width: 300px; height: 300px; margin-left: 17px;"/>
                      <div class="inner">
                          <div class="info">
                               <h5>Tshering Dorji</h5>
                               <p>Web Developer</p>
                               <div class="social-links">
                                   <a href="https://www.facebook.com/tshe.dorjee" target='_blank'><span class="fa fa-facebook"></span></a>
                                   <a href="https://www.instagram.com" target='_blank'><i class="fab fa-instagram"></i></a>
                                   <a href="https://twitter.com/" target='_blank'><span class="fa fa-twitter"></span></a>
                                   <a href="https://www.youtube.com/" target='_blank'><span class="fa fa-youtube"></span></a>
                               </div>
                          </div>
                      </div>
                  </div>
             </div>
         </div>
     </div>
  </section>
  <!-- End About Section -->

  <!-- Contact Section -->
  <section id="contact">
    <div class="contact container">
      <div>
        <h1 class="section-title">Contact <span>info</span></h1>
      </div>
      <div class="contact-items">
        <div class="contact-item">
          <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/phone.png" /></div>
          <div class="contact-info">
            <h1>Phone</h1>
            <h2>+975 17743174</h2>
            <h2>+975 12345678</h2>
          </div>
        </div>
        <div class="contact-item">
          <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/new-post.png" /></div>
          <div class="contact-info">
            <h1>Email</h1>
            <h2>12190051.gcit@rub.edu.bt</h2>
            <h2>12190053.gcit@rub.edu.bt</h2>
            <h2>12190093.gcit@rub.edu.bt</h2>
            <h2>12190105.gcit@rub.edu.bt</h2>
          </div>
        </div>
        <div class="contact-item">
          <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/map-marker.png" /></div>
          <div class="contact-info">
            <h1>Address</h1>
            <h2>Mongar, Gyalpozhing, Bhutan</h2>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Contact Section -->

  <!-- Footer -->
  <section id="footer">
    <div class="footer container">
      <div class="brand">
        <h1><span>Bhutans' Fuel </span>Price Prediction</h1>
      </div>
      <h2>Know the Fuel Prices of Bhutan</h2>
      <div class="social-icon">
        <div class="social-item">
          <a href="https://www.facebook.com/" target='_blank'><img src="https://img.icons8.com/bubbles/100/000000/facebook-new.png" /></a>
        </div>
        <div class="social-item">
          <a href="https://www.instagram.com" target='_blank'><img src="https://img.icons8.com/bubbles/100/000000/instagram-new.png" /></a>
        </div>
      </div>
      <p>© 2022 Group 12. All rights reserved</p>
    </div>
  </section>
  <!-- End Footer -->
  <script src="{% static 'js/app.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

  <script>

        config = {
            dateFormat: "Y-m-d",
            minDate: "2020-01-15",
            maxDate: "2022-04-01"
            
        }  
        flatpickr("input[type=datetime-local]", config); 

        $(document).ready(function(){
            $(".mobile-nav i").click(function(){
                $(".site-nav-menu").toggleClass("mobile-menu");
            });
        });
  </script>
</body>

</html>


 {% endcomment %}